Repository bcgov/silviculture-ipc, pull requests merged in 2020-05, with the labels that each got.

#88 Don't default 1 for number of workers
  app/frontend/package.json
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/form/OrgBookSearch.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/store/modules/form.js
  app/package.json
Labels: bug, enhancement

#90 Notes table
  app/frontend/package-lock.json
  app/frontend/vue.config.js
  app/package-lock.json
  app/src/migrations/20200505203000-5-note-table.js
  app/src/models/ipcPlan.js
  app/src/models/note.js
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: enhancement

#89 show warning if user enters business name not from Org Book
  app/frontend/src/components/form/OrgBookSearch.vue
Labels: enhancement

#91 Allow note to be added to a status in the same api call.
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: enhancement

#92 Throw Problem on save errors, handle Inspection Date timezone on backend.
  app/src/models/index.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: bug, enhancement

#87 Inspection Status and Notes
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/admin/AdminReviewSubmission.vue
  app/frontend/src/components/admin/StatusTable.vue
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/components/admin/inspection/InspectionPanel.vue
  app/frontend/src/components/admin/inspection/NotesPanel.vue
  app/frontend/src/components/admin/inspection/Status.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/components/form/Step6.vue
  app/frontend/src/plugins/vuetify.js
  app/frontend/src/services/ipcService.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/store/modules/form.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/admin/Status.vue
  app/frontend/src/views/admin/Submission.vue
  app/frontend/tests/unit/components/admin/StatusTable.spec.js
  app/frontend/tests/unit/views/admin/Status.spec.js
  app/package-lock.json
  app/package.json
  app/src/components/keycloak.js
Labels: enhancement

#94 Add Email Receipt Request feature for successful submissions
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/components/common/GeneratePdfButton.vue
  app/frontend/src/components/form/OrgBookSearch.vue
  app/frontend/src/components/form/RequestReceipt.vue
  app/frontend/src/components/form/Step6.vue
  app/frontend/src/main.js
  app/frontend/src/services/emailService.js
  app/frontend/tests/unit/services/emailService.spec.js
  app/frontend/vue.config.js
  app/nodemon.json
  app/src/assets/silvIPC_emailTemplate.html
  app/src/components/email.js
  app/src/components/validators.js
  app/src/routes/v1.js
  app/src/routes/v1/email.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1/email.spec.js
Labels: bug, enhancement

#95 Fix Admin submitted column to order by Date value instead of by string
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/components/admin/inspection/InspectionPanel.vue
Labels: bug

#93 Geocoder city location lookup feature
  app/frontend/src/components/form/CityLookup.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/store/modules/form.js
  app/src/migrations/20200511140000-6-location-lat-long-cols.js
  app/src/models/location.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: enhancement

#97 Quick Cleanup...
  app/frontend/src/store/modules/form.js
  app/src/services/dataService.js
Labels: bug

#98 Version bump to 1.1.1
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/form/CityLookup.vue
  app/frontend/src/components/form/OrgBookSearch.vue
  app/package-lock.json
  app/package.json
Labels: enhancement

#99 status and clickable submission table
  app/frontend/src/components/admin/SubmissionsTable.vue
Labels: enhancement

#101 fixed latitude and longitude miss-match
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/form/CityLookup.vue
  app/package-lock.json
  app/package.json
Labels: bug

#100 inspection dashboard
  app/config/custom-environment-variables.json
  app/config/default.json
  app/frontend/src/components/admin/Dashboard.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/router/index.js
  app/frontend/src/views/admin/Dashboard.vue
  app/frontend/src/views/admin/InspectionDashboard.vue
  app/frontend/src/views/admin/PublicDashboard.vue
  app/frontend/tests/unit/views/admin/Dashboard.spec.js
  openshift/README.md
Labels: enhancement

#102 Fix BCGov Logo being sized incorrectly on Edge Browser
  app/frontend/src/components/bcgov/BCGovHeader.vue
Labels: bug

#104 show inspection date in local timezone and inspector on submissions table
  app/frontend/src/components/admin/StatusTable.vue
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/components/admin/inspection/InspectionPanel.vue
Labels: enhancement

#105 Prevent page refresh on email enter
  app/frontend/src/components/form/RequestReceipt.vue
Labels: bug
