Repository bcgov/silviculture-ipc, pull requests merged in 2020-04, with the labels that each got.

#8 Implement data access service layer
  app/frontend/src/components/base/BaseAuthButton.vue
  app/src/routes/v1/ipc.js
  app/src/routes/v1/keycloak.js
  app/src/services/dataService.js
  app/tests/unit/routes/v1/ipc.spec.js
Labels: enhancement

#9 data service enhancement
  app/src/models/business.js
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
Labels: enhancement

#10 Implement frontend service layer for ipc calls
  app/frontend/src/components/base/BaseActionCard.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/emailService.js
  app/frontend/src/services/index.js
  app/frontend/src/services/interceptors.js
  app/frontend/src/services/ipcService.js
  app/frontend/src/services/testerService.js
  app/frontend/src/utils/constants.js
  app/frontend/tests/unit/components/admin/ApiTester.spec.js
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
  app/frontend/tests/unit/components/base/BaseDialog.spec.js
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovFooter.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovHeader.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/services/emailService.spec.js
  app/frontend/tests/unit/services/ipcService.spec.js
  app/frontend/tests/unit/services/testerService.spec.js
  app/frontend/tests/unit/store/index.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
  app/frontend/tests/unit/views/Home.spec.js
  app/frontend/tests/unit/views/NotFound.spec.js
  app/src/routes/v1.js
Labels: enhancement

#6 Feature/validation
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/components/form/Step3.vue
  app/frontend/src/components/form/Step4.vue
  app/frontend/src/components/form/Step5.vue
  app/frontend/src/components/form/Step6.vue
  app/frontend/src/store/modules/form.js
Labels: enhancement

#12 Feature/submissions table
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/views/Admin.vue
  app/src/routes/v1/ipc.js
  app/src/services/index.js
Labels: enhancement

#11 Feature/form submission
  app/frontend/src/components/form/Form.vue
  app/frontend/src/components/form/Step1.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/components/form/Step3.vue
  app/frontend/src/components/form/Step4.vue
  app/frontend/src/components/form/Step5.vue
  app/frontend/src/components/form/Step6.vue
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/Home.vue
  app/src/middleware/validation.js
Labels: enhancement

#16 Feature/ipc focused api
  app/config/default.json
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
  app/src/services/transformService.js
  app/tests/unit/routes/v1/ipc.spec.js
Labels: enhancement

#17 Bugfix save using businessId instead of ipcPlanId
  app/src/services/dataService.js
Labels: bug

#22 Add OrgBook typeahead search for business registration name
  app/config/custom-environment-variables.json
  app/config/default.json
  app/frontend/src/components/form/OrgBookSearch.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/main.js
Labels: enhancement

#23 Add CDOGS service.
  app/config/custom-environment-variables.json
  app/config/default.json
  app/package-lock.json
  app/package.json
  app/src/assets/silviculture-ipc-template-a.docx
  app/src/assets/silviculture-ipc-template-a.json
  app/src/components/cdogsService.js
  app/src/components/clientConnection.js
  app/src/components/errorToProblem.js
  app/src/components/ipcPlanPdf.js
  app/src/routes/v1/ipc.js
Labels: enhancement

#19 Add sendReceipt function in email component
  app/src/assets/silvIPC_emailTemplate.html
  app/src/components/email.js
  app/src/routes/v1/ipc.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/routes/v1/ipc.spec.js
Labels: enhancement

#37 Pipeline/enabletest
  Jenkinsfile
  app/package-lock.json
  app/package.json
  app/src/migrations/20200421000000-initialize-database.js
  app/src/models/ipcPlan.js
Labels: bug, enhancement

#38 Add missing boolean field validation
  Jenkinsfile
  app/src/components/validators.js
  app/tests/fixtures/validIPCPost.json
Labels: bug

#39 pdf download link for admin user
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/services/ipcService.js
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/Submission.vue
  app/src/components/ipcPlanPdf.js
Labels: enhancement

#42 added link to Guidance doc
  app/frontend/src/components/form/Step1.vue
Labels: enhancement

#44 Feature/covid contact biz address
  app/package.json
  app/src/components/validators.js
  app/src/migrations/20200421000000-initialize-database.js
  app/src/models/business.js
  app/src/models/contact.js
  app/src/models/ipcPlan.js
  app/src/models/location.js
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
  app/src/services/transformService.js
  app/tests/fixtures/validIPCPost.json
  app/tests/unit/routes/v1/ipc.spec.js
Labels: enhancement

#45 New location UI
  app/frontend/src/components/form/CampLocation.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/store/modules/form.js
Labels: enhancement

#53 Add configmap based email recipient functionality
  app/config/custom-environment-variables.json
  app/config/test.json
  app/src/components/email.js
  openshift/README.md
Labels: enhancement

#55 Warning msg on step 1,
  app/frontend/src/components/form/Step1.vue
  app/src/components/email.js
  app/tests/unit/components/email.spec.js
Labels: enhancement

#50 pdf button
  app/frontend/src/components/form/Step6.vue
Labels: bug, enhancement

#56 FE UI tweaks
  app/frontend/src/components/form/Step1.vue
  app/frontend/src/components/form/Step2.vue
Labels: enhancement

#59 Hide login
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
Labels: enhancement

#65 open pdf url in new tab.
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/components/form/Step6.vue
Labels: bug

#67 Fix for incorrectly escaped special characters in OrgBook search query string
  app/frontend/src/components/form/OrgBookSearch.vue
Labels: bug

#68 Feature/various
  app/frontend/src/components/form/Step1.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/components/form/Step6.vue
  app/frontend/src/plugins/vuetify.js
  app/frontend/src/router/index.js
  app/frontend/src/views/Submission.vue
Labels: bug, enhancement

#69 Implement Children Vue Routing
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/router/index.js
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/Submission.vue
  app/frontend/src/views/admin/Root.vue
  app/frontend/src/views/admin/Submission.vue
  app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
Labels: bug, enhancement

#71 add licencees free-form text to locations table
  app/src/migrations/20200427000000-1-location-licensees-col.js
  app/src/models/location.js
Labels: enhancement

#74 Add number of workers
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/admin/Submission.vue
  app/src/assets/silviculture-ipc-template-h.docx
  app/src/components/ipcPlanPdf.js
  app/src/migrations/20200428173449-2-location-worker-count-col.js
  app/src/models/location.js
Labels: enhancement

#73 Implement prop based role checking
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/router/index.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/admin/Dev.vue
  app/frontend/src/views/admin/Root.vue
  app/frontend/src/views/admin/Submission.vue
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
  app/frontend/tests/unit/views/admin/Dev.spec.js
Labels: enhancement

#75 add inspection status table.
  app/package-lock.json
  app/package.json
  app/src/migrations/20200428180000-3-inspection-status-table.js
  app/src/models/inspectionStatus.js
  app/src/models/ipcPlan.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: enhancement

#77 Add support for ipcPlan status - Create and Read (all).
  app/src/routes/v1/ipc.js
  app/src/services/dataService.js
  app/src/services/transformService.js
Labels: enhancement

#80 Bugfix hasSilvipcRoles method blocking authenticated no-role access
  app/frontend/src/store/modules/auth.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
Labels: bug

#79 Add StatusTable component support
  app/frontend/src/components/admin/StatusTable.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/ipcService.js
  app/frontend/src/views/admin/Status.vue
  app/frontend/tests/unit/components/admin/StatusTable.spec.js
  app/frontend/tests/unit/services/ipcService.spec.js
  app/frontend/tests/unit/views/admin/Status.spec.js
Labels: enhancement

#83 Feature/step3 wording
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/admin/SubmissionsTable.vue
  app/frontend/src/components/base/BaseContactCard.vue
  app/frontend/src/components/base/BaseInfoCard.vue
  app/frontend/src/components/base/BaseWarningCard.vue
  app/frontend/src/components/form/Step1.vue
  app/frontend/src/components/form/Step2.vue
  app/frontend/src/components/form/Step3.vue
  app/frontend/src/components/form/Step4.vue
  app/frontend/src/components/form/Step5.vue
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/admin/Submission.vue
  app/src/assets/silviculture-ipc-template-i.docx
  app/src/components/ipcPlanPdf.js
  app/src/migrations/20200430000000-4-ipc-formversion-col.js
  app/src/models/ipcPlan.js
Labels: enhancement
